### ISSUE TITLE
Existing External Research - dead link

### ISSUE THREAD

**Issue by Coedice** [eduvis/eduvis.github.io#10]
On the [links page under "Existing External Research"](https://eduvis.com.au/links#existing-external-research) there is a dead link. I can't find an alternative.

**Comment by njsch** [comment]
Ah. that definitely used to work but hasn't been checked for a while.

**Comment by njsch** [comment]
Removed the section on research, as the now-broken Url was the only thing in it (see commit [e9e23b9](https://github.com/eduvis/eduvis.github.io/commit/e9e23b95932027fc1e9fe3a4a97d39398eaed6d8) on the Main branch).
