### ISSUE TITLE
QUALITY-PRESENTATION: Remove unnecessary checkbox from header.

### ISSUE THREAD

**Issue by njsch** [eduvis/eduvis.github.io#3]
@briancoogan, do you know how to do this without damaging the unique and sophisticated functionality of `<nav>` in `./_includes/header.html`? Now that I've customised the whole thing, I can't get rid of it.  I was there before in the frontend but hidden to the user.  But now it pops up eery time.

**Comment by njsch** [comment]
I fixed it.

**Comment by briancoogan** [comment]
Good work!  I didn’t know anyway!
