### ISSUE TITLE
Use Adequate Fonts and Colours to Make Website More Visually Appealing

### ISSUE THREAD

**Issue by njsch** [eduvis/eduvis.github.io#4]
Closes #2.  We need to make better use of CSS with the HTML to make the website more interesting to look at for sighted users.  But I really need outside contributions to do this properly.  Probably can't use PHP / Python / Ruby as it would potentially be a violation of Github's terms of service involving Github Pages.  Although, maybe we could work around this with dev ops (CI and Buddy Works)? Just thinking out loud.

**Comment by aditya28sarin** [comment]
hey, can you assign me on this issue?

**Comment by njsch** [comment]
@aditya28sarin, Sure, done.

**Comment by aditya28sarin** [comment]
Sorry, I am not that familiar with Ruby and your paths are also not relative. I am un-assigning myself. Will surely try to help somewhere else.

**Comment by njsch** [comment]
Okay that’s fine, although you shouldn’t need to write any Ruby. I have not written anything  in Ruby throughout the entire building of the website.  I have simply use the already existing backend to convert from markdown to HTML. The styles are based on @Jekyll/minima.
