### ISSUE TITLE
Create Contact Form for "Contact Us" Page

### ISSUE THREAD

**Issue by njsch** [eduvis/eduvis.github.io#5]
It would be better if the site had a contact form for queries rather than just straight email addresses.  Could do this in PHP but not sure if that's ethically viable for security and policy reasons.  Might end up moving this site elsewhere anyway due to obvious potential limitations for multiple reasons.  Maybe use formspree?

Any thoughts @briancoogan, @kylekeane?

**Comment by njsch** [comment]
Closed #5.  Completed a while ago.

**Comment by briancoogan** [comment]
Would probably do conventional hosting. Either cPanel or a small linode
serverlet. Whatever is easiest for yourself, and it’s not a huge step up
from GitHub hosting now you’re aware of some of the ideas. Was actually
impressed you were using GitHub hosting so adroitly.

Contact forms always better. Best to protect with invisible Recaptcha.

Don’t understand what you mean by “ethically viable for security/policy
reasons”.

Happy for you to call if quicker.
0402 325 348

Brian
