### ISSUE TITLE
EduVis/Eduvis capitalisation

### ISSUE THREAD

**Issue by Coedice** [eduvis/eduvis.github.io#9]
I see in some places in the website the title is EduVis, and in other places it is Eduvis. Which one should we stick with?

**Comment by njsch** [comment]
Charlie uses Eduvis, so we should probably stick with that. But the reason why it's not consistent is because Camel and Pascal-case are read out by some screen-readers and speech synthesises as whitespaced whole words so it makes more sense to me.
